#!/usr/bin/env python3
"""Score a TAAC2025-style result.json against local ground truth.

Preliminary / single-positive metric:
    Score = 0.31 * HitRate@10 + 0.69 * NDCG@10

Second-stage / multi-behavior metric:
    wHitRate@10 and wNDCG@10 use action weights:
      exposure=0, click=1, conversion=alpha
    Score uses the same 0.31/0.69 weighting.

This script is for local validation. The public test set does not include
ground truth, but local validation data generated by this repo's converters does.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compute TAAC2025 metrics for a local result.json")
    parser.add_argument("--result-json", required=True, help="Path to result.json")
    parser.add_argument("--truth-json", required=True, help="Path to local ground_truth.json")
    parser.add_argument("--round", choices=["preliminary", "second"], default="preliminary")
    parser.add_argument("--k", type=int, default=10)
    parser.add_argument("--conversion-weight", type=float, default=2.5)
    return parser.parse_args()


def action_weight(action_type: int, conversion_weight: float) -> float:
    if int(action_type) == 2:
        return float(conversion_weight)
    if int(action_type) == 1:
        return 1.0
    return 0.0


def normalize_user_id(value: Any) -> str:
    return str(value)


def normalize_truth(value: Any) -> List[Tuple[str, int]]:
    """Return [(creative_id, action_type), ...]."""
    if isinstance(value, list):
        out = []
        for item in value:
            if isinstance(item, dict):
                out.append((str(item["creative_id"]), int(item.get("action_type", 1))))
            else:
                out.append((str(item), 1))
        return out
    if isinstance(value, dict):
        return [(str(value["creative_id"]), int(value.get("action_type", 1)))]
    return [(str(value), 1)]


def load_predictions(path: Path) -> Dict[str, List[str]]:
    with open(path, "r", encoding="utf-8") as f:
        result = json.load(f)
    users = result.get("user") or result.get("users")
    top10s = result.get("top10s")
    if users is None or top10s is None:
        raise ValueError("result.json must contain `user` and `top10s` fields.")
    if len(users) != len(top10s):
        raise ValueError(f"`user` length {len(users)} != `top10s` length {len(top10s)}")
    return {
        normalize_user_id(user_id): [str(item) for item in recs]
        for user_id, recs in zip(users, top10s)
    }


def dcg_gain(rank_1based: int, weight: float = 1.0) -> float:
    return float(weight) / math.log2(rank_1based + 1)


def score_preliminary(preds: Dict[str, List[str]], truth: Dict[str, List[Tuple[str, int]]], k: int) -> Dict[str, float]:
    hit_sum = 0.0
    ndcg_sum = 0.0
    count = 0

    for user_id, targets in truth.items():
        if not targets:
            continue
        target = targets[0][0]
        recs = preds.get(user_id, [])[:k]
        count += 1
        for rank, item in enumerate(recs, start=1):
            if item == target:
                hit_sum += 1.0
                ndcg_sum += dcg_gain(rank)
                break

    hitrate = hit_sum / count if count else 0.0
    ndcg = ndcg_sum / count if count else 0.0
    score = 0.31 * hitrate + 0.69 * ndcg
    return {"Score": score, f"HitRate@{k}": hitrate, f"NDCG@{k}": ndcg, "n": float(count)}


def score_second(
    preds: Dict[str, List[str]],
    truth: Dict[str, List[Tuple[str, int]]],
    k: int,
    conversion_weight: float,
) -> Dict[str, float]:
    whr_sum = 0.0
    wndcg_sum = 0.0
    count = 0

    for user_id, targets in truth.items():
        weights = {
            creative_id: max(action_weight(action, conversion_weight), 0.0)
            for creative_id, action in targets
        }
        weights = {creative_id: weight for creative_id, weight in weights.items() if weight > 0}
        if not weights:
            continue

        denom = sum(weights.values())
        ideal_weights = sorted(weights.values(), reverse=True)[:k]
        idcg = sum(dcg_gain(rank, weight) for rank, weight in enumerate(ideal_weights, start=1))
        if denom <= 0 or idcg <= 0:
            continue

        seen_hits = set()
        hit_weight = 0.0
        dcg = 0.0
        for rank, item in enumerate(preds.get(user_id, [])[:k], start=1):
            if item in weights and item not in seen_hits:
                seen_hits.add(item)
                weight = weights[item]
                hit_weight += weight
                dcg += dcg_gain(rank, weight)

        whr_sum += hit_weight / denom
        wndcg_sum += dcg / idcg
        count += 1

    whitrate = whr_sum / count if count else 0.0
    wndcg = wndcg_sum / count if count else 0.0
    score = 0.31 * whitrate + 0.69 * wndcg
    return {"Score": score, f"wHitRate@{k}": whitrate, f"wNDCG@{k}": wndcg, "n": float(count)}


def main() -> None:
    args = parse_args()
    preds = load_predictions(Path(args.result_json))
    with open(args.truth_json, "r", encoding="utf-8") as f:
        raw_truth = json.load(f)
    truth = {normalize_user_id(user_id): normalize_truth(value) for user_id, value in raw_truth.items()}

    if args.round == "preliminary":
        metrics = score_preliminary(preds, truth, args.k)
    else:
        metrics = score_second(preds, truth, args.k, args.conversion_weight)

    print(json.dumps(metrics, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
